### ISSUE TITLE
Ego pose height is wrong?

### ISSUE THREAD

**Issue by alliecc** [carla-simulator/data-collector#12]
Hi, 
I generated a dataset with data-collector. This repo doesn't provide 3D point cloud map so I got it from latest carla repo. However, when I try to visualize the trajectory with point cloud map, it looks like the height is incorrect. 

I guess it's either CARLA Gear uses different point cloud map with latest version, or the ego pose height here is incorrect. Could you help with this? Thanks!

Attached the visualized trajectory and point cloud map from "Town01.pcd"

![Screenshot from 2019-09-24 15-38-06](https://user-images.githubusercontent.com/25491448/65544506-5b2a0880-dee1-11e9-80c5-7b457b07f0aa.png)

**Comment by felipecode** [comment]
I think carla height was corrected in some version !.
Nice plot btw

**Comment by alliecc** [comment]
Thanks for quick reply! You mean the carla height was corrected sometime after version 0.8.4? Do you know in which version it was corrected? By the way I found all the heights in "waypoints_world" are 22 and all the z values in ego pose are around 38.1.

**Comment by alliecc** [comment]
This answered my question https://github.com/carla-simulator/carla/issues/541. I will close the issue. Btw, thanks for this cool data collector!
