### ISSUE TITLE
Start a CARLA Gear Server error

### ISSUE THREAD

**Issue by timswim** [carla-simulator/data-collector#13]
Normal start CarlaGear working well (./CarlaUE4.sh). But when I try to execute a command
sh CarlaUE4.sh /Game/Maps/Town01 -windowed -world-port=2000  -benchmark -fps=10
for a moment, a black window appears and I get this error
![Снимок](https://user-images.githubusercontent.com/36427013/73669412-72130f80-46b8-11ea-93c5-cccaa229666e.JPG)
![Снимок2](https://user-images.githubusercontent.com/36427013/73669413-72aba600-46b8-11ea-820a-60b75a203209.JPG)
What caused this error? could you help me?

**Comment by timswim** [comment]
I'm sorry, I found a mistake

**Comment by SExpert12** [comment]
Can we collect the data using normal CARLA server instead of CARLA-gear server. Do you know about this?
